# Site settings
title: hans mayer's weblog
email: blog.15@ma.yer.at
description: "here you can find this and that - probably most related to UNIX/Linux and network"
baseurl: ""
url: "http://blog.mayer.tv"
github_username:  hans-mayer

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title.html
gems:
  - jekyll-sitemap

